### ISSUE TITLE
Choose no. of entries in the frontend

### ISSUE THREAD

**Issue by SimonPhumin** [winkm89/teachPress#102]
Hi, 
I was wondering if teachPress offers any functionality to change the no. of publications via dropdown in the frontend. I am able to change the no of entries on the first page with the tp_cloud shortcode and a simple html select dropdown (PHP isset). But it wont work on any following page when I set a filter, e.g. year to 2018 which has more entries than specified before. Let's say I set `'entries_per_page' => 10` and have 50 publications, it would create 5 new pages and display the pagination. When I select the second page it always says: "No publications matched your criteria.". But when I then select "10 entries per page" from my custom dropdown it shows the second page.

Is there any simple way to implement a "no. of entries" select in combination with the tp_cloud filters?  This would be a great feature.

**Comment by winkm89** [comment]
Hi Simon,
It sounds like, that your code just forget the number of entries under some conditions. So "No publications matched your criteria." is maybe caused by an entries_per_page value of 0. If you uncomment the [line 1717 in /core/database.php](https://github.com/winkm89/teachPress/blob/master/core/database.php#L1717) you will see the SQL statement. Maybe that shows you the problem.

**Comment by SimonPhumin** [comment]
Hi Michael, thanks for your comment. Actually its working now as expected. I added an optional `<select><option>` dropdown to choose the no. of entries on every page and modified `$link_attributes` and the `$filter_parameter` array in `shortcodes.php`.
