### ISSUE TITLE
tpcloud show_{whatever}_filter not working(?)

### ISSUE THREAD

**Issue by abrow169** [winkm89/teachPress#103]
Hi, I would just like to start with the fact that I have no real idea what I'm doing, so most likely I did something stupid. 
My ultimate goal is to have the tags cloud and a search menu. Right now I'm working on disabling the dropdown menu that tpcloud has and I thought I could just say:
[tpcloud  show_author_filter="0" show_type_filter="0"]

but as soon as I say that, tpcloud just breaks. I checked and I have the most updated version of teachpress. 
Please and Thank You,
Alisa

**Comment by winkm89** [comment]
Hi Alisa,
The problem is just the double blank space after "tpcloud". It's a bit strange, but it works without it:
`[tpcloud show_author_filter="0" show_type_filter="0"]`

> My ultimate goal is to have the tags cloud and a search menu.
Unfortunately, that's one of the things which are not implemented in the frontend. It's not impossible to do it. But not without writing some PHP code.

**Comment by abrow169** [comment]
Good luck on your goal and thanks, it works now. I forget how the smallest things can throw code off so much,
