### ISSUE TITLE
tplist on different elementor tabs-Links and Bibtex buttons don't work

### ISSUE THREAD

**Issue by vdimakopoulos** [winkm89/teachPress#167]
Thank you for this amazing plugin.
I am using the tplist shortcodes on different elementor tabs.
Specifically, I have categorized my publications based on tags and I would like to display each category on different tabs.

Everything works fine except for the links and bibtex button.
It seems that on the first tab everything works great. On the rest when I click the buttons dont work. 
From inspection of elements I found out that the function teachpress_pub_showhide doesn't do any action, namely doesn't trigger the display of the block. 

Any insight on how to fix this issue? 

Visit my [website ](https://hfozuri.ch/publications/) for further insights of the problem.

Thank you in advance.

**Comment by winkm89** [comment]
Hi,
The problem is simple: If you are using multiple tplist elements on a page, then the HTML element IDs on the page are no longer unique if a publication is displayed more than one time. So, the script doesn't know which container should be displayed, if you click on the links.
The solution is simple: You can give every tplist shortcode a different **container suffix.** Example:
`[tplist container_suffix="b"]`
In your case you need a suffix at least for the first shortcode in the "All" tab.

**Comment by vdimakopoulos** [comment]
Thank you so much for your quick reply.
It seems the problem was solved when I used different container suffixes for the tabs.
