### ISSUE TITLE
Tag 8.1.7 is missing

### ISSUE THREAD

**Issue by nise** [winkm89/teachPress#204]
I've installed Version 8.1.7 but cannot see this version here in the repo.

**Comment by winkm89** [comment]
8.1.6 and 8.1.7 were backports from the code of the primary dev branch here on Github, which is currently a 9.0 alpha. I haven't a separate branch from 8.1.x here because I haven't planned to develop 8.1 and 9.0 separately. 
But sometimes a user comes up with a problem or discovers a bug, so I put an intermediate version on the wordpress.org release channel, which were not here published separately.
