### ISSUE TITLE
DOI and URL

### ISSUE THREAD

**Issue by SamyStyle** [winkm89/teachPress#72]
Whenever a doi is in the doi-key as well as in the URL-key the link to the one DOI gets displayed twice. Sadly a number of online BibTeX generate are doing so.

It would be very handy if teachPress would check for duplicate URLs before displaying all of them.

**Comment by winkm89** [comment]
Thanks for the pull request. :)

**Comment by paulrosee** [comment]
I am using Wordpress 4.9 and upgraded teachPress to 6.2.0. After activating teachPress, I get the following error:

"Plugin could not be activated because it triggered a fatal error.

Parse error: syntax error, unexpected '[' in /hp/bk/ac/mv/www/paul/wordpress/wp-content/plugins/teachpress/core/templates.php on line 475"

This line is one of the lines, changed by the above post. In addition, if I change the file "templates.php" back to the one of teachPress 6.0.4, everything seems work.

**Comment by winkm89** [comment]
It seems that there is a problem with the array declaration in this line:

```php
$url_displayed = [];
```
This doesn't work in PHP 5.3 or older. I see no problems with PHP 5.6 o PHP 7. The question is: works teachPress 6.2, if you change line 475 to the following?

```php
$url_displayed = array();
```

**Comment by paulrosee** [comment]
Thank you for the swift reply. Yes this line and the PHP version was the issue. I was not aware that on the actual webspace the PHP version was still 5.3. Changing the respective line worked as well as updating PHP to 5.6 or later.
